In [2]:
from sklearn.utils import shuffle
import numpy as np
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import SGD

In [3]:
M = 2 #input dimension
K = 3 #class size
n = 100 #number of data
N = n * K #all data

In [4]:
X1 = np.random.randn(n, M) + np.array([0, 10])
X2 = np.random.randn(n, M) + np.array([5, 5])
X3 = np.random.randn(n, M) + np.array([10, 0])
Y1 = np.array([[1, 0, 0] for i in range(n)])
Y2 = np.array([[0, 1, 0] for i in range(n)])
Y3 = np.array([[0, 0, 1] for i in range(n)])

X = np.concatenate((X1, X2, X3), axis = 0)
Y = np.concatenate((Y1, Y2, Y3), axis = 0)

In [6]:
model = Sequential()
model.add(Dense(input_dim=M, units = K))
model.add(Activation('softmax'))

model.compile(loss='categorical_crossentropy', optimizer=SGD(lr=0.1))

In [7]:
#mini batch
minibatch_size=50
model.fit(X, Y, epochs=20, batch_size=minibatch_size)

Epoch 1/20
300/300 [==============================] - 9s 31ms/step - loss: 1.2605
Epoch 2/20
300/300 [==============================] - 0s 43us/step - loss: 0.2301
Epoch 3/20
300/300 [==============================] - 0s 50us/step - loss: 0.1517
Epoch 4/20
300/300 [==============================] - 0s 43us/step - loss: 0.1202
Epoch 5/20
300/300 [==============================] - 0s 47us/step - loss: 0.0975
Epoch 6/20
300/300 [==============================] - 0s 50us/step - loss: 0.0840
Epoch 7/20
300/300 [==============================] - 0s 50us/step - loss: 0.0748
Epoch 8/20
300/300 [==============================] - 0s 53us/step - loss: 0.0663
Epoch 9/20
300/300 [==============================] - 0s 50us/step - loss: 0.0605
Epoch 10/20
300/300 [==============================] - 0s 46us/step - loss: 0.0556
Epoch 11/20
300/300 [==============================] - 0s 37us/step - loss: 0.0513
Epoch 12/20
300/300 [==============================] - 0s 40us/step - loss: 0.0483
Epoch 13/20
3

In [8]:
X_, Y_ = shuffle(X, Y)
classes = model.predict_classes(X_[0:10], batch_size=minibatch_size)
prob = model.predict_proba(X_[1:10], batch_size=1)

print(classes)
print(prob)

[2 1 2 1 2 2 0 0 0 0]
[[1.21370815e-01 8.77377570e-01 1.25168962e-03]
 [7.29264684e-08 5.80095612e-02 9.41990376e-01]
 [4.71717026e-03 9.80791748e-01 1.44910701e-02]
 [1.48598122e-06 4.10231985e-02 9.58975315e-01]
 [8.18694224e-10 4.79229400e-03 9.95207727e-01]
 [9.99088287e-01 9.11697221e-04 4.25364605e-11]
 [9.96160030e-01 3.83999292e-03 2.07374917e-08]
 [9.91789222e-01 8.21075030e-03 4.42973160e-08]
 [9.85739410e-01 1.42605491e-02 3.89322485e-09]]
